// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.2
// source: mngrinfo.proto

package mngrinfo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvAManagerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vmid string `protobuf:"bytes,1,opt,name=vmid,proto3" json:"vmid,omitempty"`
}

func (x *AvAManagerInfoRequest) Reset() {
	*x = AvAManagerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mngrinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvAManagerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvAManagerInfoRequest) ProtoMessage() {}

func (x *AvAManagerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mngrinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvAManagerInfoRequest.ProtoReflect.Descriptor instead.
func (*AvAManagerInfoRequest) Descriptor() ([]byte, []int) {
	return file_mngrinfo_proto_rawDescGZIP(), []int{0}
}

func (x *AvAManagerInfoRequest) GetVmid() string {
	if x != nil {
		return x.Vmid
	}
	return ""
}

type AvAManagerInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GpuUuid    string `protobuf:"bytes,1,opt,name=gpu_uuid,json=gpuUuid,proto3" json:"gpu_uuid,omitempty"`
	MngrAddr   string `protobuf:"bytes,2,opt,name=mngr_addr,json=mngrAddr,proto3" json:"mngr_addr,omitempty"`
	WorkerPort uint32 `protobuf:"varint,3,opt,name=worker_port,json=workerPort,proto3" json:"worker_port,omitempty"`
}

func (x *AvAManagerInfoReply) Reset() {
	*x = AvAManagerInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mngrinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvAManagerInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvAManagerInfoReply) ProtoMessage() {}

func (x *AvAManagerInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_mngrinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvAManagerInfoReply.ProtoReflect.Descriptor instead.
func (*AvAManagerInfoReply) Descriptor() ([]byte, []int) {
	return file_mngrinfo_proto_rawDescGZIP(), []int{1}
}

func (x *AvAManagerInfoReply) GetGpuUuid() string {
	if x != nil {
		return x.GpuUuid
	}
	return ""
}

func (x *AvAManagerInfoReply) GetMngrAddr() string {
	if x != nil {
		return x.MngrAddr
	}
	return ""
}

func (x *AvAManagerInfoReply) GetWorkerPort() uint32 {
	if x != nil {
		return x.WorkerPort
	}
	return 0
}

var File_mngrinfo_proto protoreflect.FileDescriptor

var file_mngrinfo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x6e, 0x67, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x6e, 0x67, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x2b, 0x0a, 0x15, 0x41, 0x76,
	0x41, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x76, 0x6d, 0x69, 0x64, 0x22, 0x6e, 0x0a, 0x13, 0x41, 0x76, 0x41, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x70, 0x75, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x70, 0x75, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6e, 0x67,
	0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6e,
	0x67, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x32, 0x67, 0x0a, 0x0e, 0x41, 0x76, 0x41, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x55, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x41, 0x76, 0x41, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f,
	0x2e, 0x6d, 0x6e, 0x67, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x41, 0x76, 0x41, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x6d, 0x6e, 0x67, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x41, 0x76, 0x41, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x3f, 0x0a, 0x19, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2e, 0x6d, 0x6e, 0x67, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0x13, 0x41,
	0x76, 0x41, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x6d, 0x6e, 0x67, 0x72, 0x69, 0x6e, 0x66,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mngrinfo_proto_rawDescOnce sync.Once
	file_mngrinfo_proto_rawDescData = file_mngrinfo_proto_rawDesc
)

func file_mngrinfo_proto_rawDescGZIP() []byte {
	file_mngrinfo_proto_rawDescOnce.Do(func() {
		file_mngrinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_mngrinfo_proto_rawDescData)
	})
	return file_mngrinfo_proto_rawDescData
}

var file_mngrinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mngrinfo_proto_goTypes = []interface{}{
	(*AvAManagerInfoRequest)(nil), // 0: mngrinfo.AvAManagerInfoRequest
	(*AvAManagerInfoReply)(nil),   // 1: mngrinfo.AvAManagerInfoReply
}
var file_mngrinfo_proto_depIdxs = []int32{
	0, // 0: mngrinfo.AvAManagerInfo.GetAvAManagerInfo:input_type -> mngrinfo.AvAManagerInfoRequest
	1, // 1: mngrinfo.AvAManagerInfo.GetAvAManagerInfo:output_type -> mngrinfo.AvAManagerInfoReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mngrinfo_proto_init() }
func file_mngrinfo_proto_init() {
	if File_mngrinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mngrinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvAManagerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mngrinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvAManagerInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mngrinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mngrinfo_proto_goTypes,
		DependencyIndexes: file_mngrinfo_proto_depIdxs,
		MessageInfos:      file_mngrinfo_proto_msgTypes,
	}.Build()
	File_mngrinfo_proto = out.File
	file_mngrinfo_proto_rawDesc = nil
	file_mngrinfo_proto_goTypes = nil
	file_mngrinfo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AvAManagerInfoClient is the client API for AvAManagerInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AvAManagerInfoClient interface {
	GetAvAManagerInfo(ctx context.Context, in *AvAManagerInfoRequest, opts ...grpc.CallOption) (*AvAManagerInfoReply, error)
}

type avAManagerInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewAvAManagerInfoClient(cc grpc.ClientConnInterface) AvAManagerInfoClient {
	return &avAManagerInfoClient{cc}
}

func (c *avAManagerInfoClient) GetAvAManagerInfo(ctx context.Context, in *AvAManagerInfoRequest, opts ...grpc.CallOption) (*AvAManagerInfoReply, error) {
	out := new(AvAManagerInfoReply)
	err := c.cc.Invoke(ctx, "/mngrinfo.AvAManagerInfo/GetAvAManagerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvAManagerInfoServer is the server API for AvAManagerInfo service.
type AvAManagerInfoServer interface {
	GetAvAManagerInfo(context.Context, *AvAManagerInfoRequest) (*AvAManagerInfoReply, error)
}

// UnimplementedAvAManagerInfoServer can be embedded to have forward compatible implementations.
type UnimplementedAvAManagerInfoServer struct {
}

func (*UnimplementedAvAManagerInfoServer) GetAvAManagerInfo(context.Context, *AvAManagerInfoRequest) (*AvAManagerInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvAManagerInfo not implemented")
}

func RegisterAvAManagerInfoServer(s *grpc.Server, srv AvAManagerInfoServer) {
	s.RegisterService(&_AvAManagerInfo_serviceDesc, srv)
}

func _AvAManagerInfo_GetAvAManagerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvAManagerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvAManagerInfoServer).GetAvAManagerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mngrinfo.AvAManagerInfo/GetAvAManagerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvAManagerInfoServer).GetAvAManagerInfo(ctx, req.(*AvAManagerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AvAManagerInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mngrinfo.AvAManagerInfo",
	HandlerType: (*AvAManagerInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvAManagerInfo",
			Handler:    _AvAManagerInfo_GetAvAManagerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mngrinfo.proto",
}
