// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.2
// source: gpuresc.proto

package gpuresc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memory map[string]uint32 `protobuf:"bytes,1,rep,name=memory,proto3" json:"memory,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // memory in MB
}

func (x *ResourceReply) Reset() {
	*x = ResourceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpuresc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReply) ProtoMessage() {}

func (x *ResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_gpuresc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReply.ProtoReflect.Descriptor instead.
func (*ResourceReply) Descriptor() ([]byte, []int) {
	return file_gpuresc_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceReply) GetMemory() map[string]uint32 {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_gpuresc_proto protoreflect.FileDescriptor

var file_gpuresc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x70, 0x75, 0x72, 0x65, 0x73, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x67, 0x70, 0x75, 0x72, 0x65, 0x73, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3a, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x70, 0x75, 0x72, 0x65, 0x73,
	0x63, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x1a, 0x39, 0x0a, 0x0b, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x4d,
	0x0a, 0x07, 0x47, 0x50, 0x55, 0x52, 0x65, 0x73, 0x63, 0x12, 0x42, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x47, 0x50, 0x55, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x70, 0x75, 0x72, 0x65, 0x73, 0x63, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x36, 0x0a,
	0x18, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x2e, 0x67, 0x70, 0x75, 0x72, 0x65, 0x73, 0x63, 0x42, 0x0c, 0x47, 0x50, 0x55, 0x52, 0x65,
	0x73, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x67, 0x70,
	0x75, 0x72, 0x65, 0x73, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gpuresc_proto_rawDescOnce sync.Once
	file_gpuresc_proto_rawDescData = file_gpuresc_proto_rawDesc
)

func file_gpuresc_proto_rawDescGZIP() []byte {
	file_gpuresc_proto_rawDescOnce.Do(func() {
		file_gpuresc_proto_rawDescData = protoimpl.X.CompressGZIP(file_gpuresc_proto_rawDescData)
	})
	return file_gpuresc_proto_rawDescData
}

var file_gpuresc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gpuresc_proto_goTypes = []interface{}{
	(*ResourceReply)(nil), // 0: gpuresc.ResourceReply
	nil,                   // 1: gpuresc.ResourceReply.MemoryEntry
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_gpuresc_proto_depIdxs = []int32{
	1, // 0: gpuresc.ResourceReply.memory:type_name -> gpuresc.ResourceReply.MemoryEntry
	2, // 1: gpuresc.GPUResc.GetGPUResource:input_type -> google.protobuf.Empty
	0, // 2: gpuresc.GPUResc.GetGPUResource:output_type -> gpuresc.ResourceReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gpuresc_proto_init() }
func file_gpuresc_proto_init() {
	if File_gpuresc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gpuresc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gpuresc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gpuresc_proto_goTypes,
		DependencyIndexes: file_gpuresc_proto_depIdxs,
		MessageInfos:      file_gpuresc_proto_msgTypes,
	}.Build()
	File_gpuresc_proto = out.File
	file_gpuresc_proto_rawDesc = nil
	file_gpuresc_proto_goTypes = nil
	file_gpuresc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GPURescClient is the client API for GPUResc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GPURescClient interface {
	GetGPUResource(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResourceReply, error)
}

type gPURescClient struct {
	cc grpc.ClientConnInterface
}

func NewGPURescClient(cc grpc.ClientConnInterface) GPURescClient {
	return &gPURescClient{cc}
}

func (c *gPURescClient) GetGPUResource(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResourceReply, error) {
	out := new(ResourceReply)
	err := c.cc.Invoke(ctx, "/gpuresc.GPUResc/GetGPUResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GPURescServer is the server API for GPUResc service.
type GPURescServer interface {
	GetGPUResource(context.Context, *emptypb.Empty) (*ResourceReply, error)
}

// UnimplementedGPURescServer can be embedded to have forward compatible implementations.
type UnimplementedGPURescServer struct {
}

func (*UnimplementedGPURescServer) GetGPUResource(context.Context, *emptypb.Empty) (*ResourceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGPUResource not implemented")
}

func RegisterGPURescServer(s *grpc.Server, srv GPURescServer) {
	s.RegisterService(&_GPUResc_serviceDesc, srv)
}

func _GPUResc_GetGPUResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPURescServer).GetGPUResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpuresc.GPUResc/GetGPUResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPURescServer).GetGPUResource(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GPUResc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gpuresc.GPUResc",
	HandlerType: (*GPURescServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGPUResource",
			Handler:    _GPUResc_GetGPUResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gpuresc.proto",
}
